import { describe, it, expect } from "vitest";
import vectors from "./vectors.json";
import { bytesToBits, bitsToBytes } from "../src/dsp/bits";
import { crc32 } from "../src/dsp/crc";
import { frameBlock, deframeBlock, HEADER_SIZE } from "../src/dsp/framing";
import { modulateFsk, demodulateFsk } from "../src/dsp/fsk";

// Each test asserts the TS port matches the Python reference (vectors.json,
// regenerated by python/tests/gen_vectors.py).

describe("bits", () => {
  it("bytesToBits matches reference", () => {
    const { bytes, bits } = vectors.bytesToBits;
    expect(bytesToBits(bytes)).toEqual(bits);
  });
  it("bitsToBytes is the inverse", () => {
    const { bytes, bits } = vectors.bytesToBits;
    expect(Array.from(bitsToBytes(bits))).toEqual(bytes);
  });
});

describe("crc32", () => {
  for (const [name, c] of Object.entries(vectors.crc32)) {
    it(`matches reference: ${name}`, () => {
      expect(crc32((c as any).bytes)).toBe((c as any).crc);
    });
  }
});

describe("framing (RS off)", () => {
  it("frameBlock matches reference bytes", () => {
    const { payload, seq, framed } = vectors.frameRsOff;
    expect(Array.from(frameBlock(Uint8Array.from(payload), seq))).toEqual(framed);
  });
  it("deframeBlock recovers payload + seq", () => {
    const { payload, seq, framed } = vectors.frameRsOff;
    const r = deframeBlock(Uint8Array.from(framed));
    expect(r).not.toBeNull();
    expect(r!.seq).toBe(seq);
    expect(Array.from(r!.payload)).toEqual(payload);
  });
  it("rejects a corrupted block (bad CRC)", () => {
    const { framed } = vectors.frameRsOff;
    const bad = Uint8Array.from(framed);
    bad[HEADER_SIZE] ^= 0xff; // flip the first payload byte
    expect(deframeBlock(bad)).toBeNull();
  });
});

describe("FSK", () => {
  const p = {
    sampleRate: vectors.fsk.params.sampleRate,
    baud: vectors.fsk.params.baud,
    f0: vectors.fsk.params.f0,
    f1: vectors.fsk.params.f1,
  };
  it("modulate matches reference audio (float tolerance)", () => {
    const audio = modulateFsk(Uint8Array.from(vectors.fsk.bytes), p);
    const ref = vectors.fsk.audio;
    expect(audio.length).toBe(ref.length);
    let maxErr = 0;
    for (let i = 0; i < ref.length; i++) maxErr = Math.max(maxErr, Math.abs(audio[i] - ref[i]));
    expect(maxErr).toBeLessThan(1e-6);
  });
  it("demodulate recovers the reference bits", () => {
    const audio = modulateFsk(Uint8Array.from(vectors.fsk.bytes), p);
    expect(demodulateFsk(audio, p)).toEqual(vectors.fsk.demodBits);
  });
  it("round-trips bytes through frame → modulate → demodulate → deframe", () => {
    const payload = Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8]);
    const framed = frameBlock(payload, 42);
    const audio = modulateFsk(framed, p);
    const bytes = bitsToBytes(demodulateFsk(audio, p));
    const r = deframeBlock(bytes.subarray(0, framed.length));
    expect(r).not.toBeNull();
    expect(r!.seq).toBe(42);
    expect(Array.from(r!.payload)).toEqual(Array.from(payload));
  });
});
